### PR TITLE
use cross-spawn to call mocha

### LINKED ISSUE #46: Unable to use gulp-mocha on Windows with large trees
Related https://github.com/sindresorhus/gulp-mocha/issues/165. I've tried https://github.com/sindresorhus/gulp-mocha/issues/154#issuecomment-281658710 (enabling `LongPathsEnabled` in registry) and https://github.com/sindresorhus/gulp-mocha/issues/165#issuecomment-399408382 (passing `recursive: true`).

### PR DESCRIPTION
**Pull request by gingur**
this still requires additional testing, but I figured I'd get the ball rolling if someone wants to take it from here. resolves https://github.com/godaddy/godaddy-test-tools/issues/46

### CODE REVIEW

**Review by DullReferenceException — APPROVED** [review]
I love it. Might be worth publishing this as a beta version so we can try it out on various projects.

**Comment by rxmarbles** [comment]
LGTM

**Review by rxmarbles — APPROVED** [review]
LGTM

**Comment by samshull** [comment]
Published as `godaddy-test-tools@14.0.0-beta` for testing

**Review by samshull — APPROVED** [review]

**Comment by samshull** [comment]
Published as `godaddy-test-tools@14.0.0`. Thanks for the PR!

**Pull request merged**
